### ISSUE TITLE
Initial view controller, and then navigate to the swipe view later on

### ISSUE THREAD

**Issue by LitenApe** [fortmarek/SwipeViewController#12]
As the title implies, i want to have an initial view, lets say a log in screen before i arrive at the swipe view controller, how can i achieve this?

**Comment by fortmarek** [comment]
Try something like this and put it inside viewDidAppear function of your SwipeViewController: 
```swift
let vc = UIViewController()
        vc.view.backgroundColor = UIColor.whiteColor()
        vc.modalPresentationStyle = UIModalPresentationStyle.OverCurrentContext
        
        self.presentViewController(vc, animated: false, completion: nil)
```

**Comment by LitenApe** [comment]
It didnt work out, but i was able to make my own replika after taking a quick look on how things work.
But thx for trying :)

**Comment by fortmarek** [comment]
I'm glad it worked out, I hope it serves you well.

**Comment by alaxicsmith** [comment]
What was the solution you found to this?

**Comment by LitenApe** [comment]
It was a really hackis solution that broke a few days later, sry if i got your hopes up :(
