### ISSUE TITLE
Custom navigation button / Go To Page functionality

### ISSUE THREAD

**Issue by rochestb** [fortmarek/SwipeViewController#14]
Is there a way to create custom buttons so you can manually go to a page?

Looks like I can use `pushViewController`?

**Comment by fortmarek** [comment]
I am not entirely sure where you want your button to be and what page you want to go to. If you want to have it in view controller equal to tab number one and on buttonTapped you want to go to eg. tab number three, the easiest way would be to make a protocol with this function:
```swift
func switchTabs(sender: UIButton) {
        
        let index = sender.tag - 1
        
        //Can't animate twice to the same controller (otherwise weird stuff happens)
        guard index != finalPageIndex && index != currentPageIndex - 1 && animationFinished else {return}

        animationFinished = false
        finalPageIndex = index
        scrollToNextViewController(index)
    }
```
and then simply implement it in the view controller you want to use for the button.

But yeah, you can use `pushViewController `, I just would not advise it to use it for moving between tabs.

**Comment by fortmarek** [comment]
Please, tell me if you found what you were looking for, so I can close this issue.

**Comment by fortmarek** [comment]
Will close for now.
