### ISSUE TITLE
Display title on top of the tabs name

### ISSUE THREAD

**Issue by Yungbubu** [fortmarek/SwipeViewController#15]
Hi All ! 

Is there a way to display a general title on top of the tab's names ?

I tried to define a title when I am building my Navigation Bar programmatically, but no title is showing on top of mu three tab's names. 

I suspect what I am doing does not work because the  SwipeViewController uses the Navbar's Title to display tab's names.

Thanks !

**Comment by fortmarek** [comment]
Yes, you are right. If you want to display the title, you don't have to subclass navigation controller. 

You can definitely use the code and implement it for your situation (again, without subclassing navigation controller)
