### ISSUE TITLE
Swift 3 Support.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [fortmarek/SwipeViewController#17]
Is this library support Swift 3?

**Comment by fortmarek** [comment]
Check out branch swift3.

**Comment by Rashesh-Bosamiya** [comment]
Is this library add buttons in the navigation bar?

**Comment by fortmarek** [comment]
Yes, that is its main feature.

**Comment by Rashesh-Bosamiya** [comment]
Okay, Thanks.

By the way, where are you from?

**Comment by fortmarek** [comment]
Czech Republic 🇨🇿  Hope the module will serve you well, hit me up if you stumble upon any problem.

**Comment by Rashesh-Bosamiya** [comment]
Thank you!
