### ISSUE TITLE
Put the left swipe button close to the left side of the navigation view, and so does the right side of the navigation view.

### ISSUE THREAD

**Issue by dearyuho** [fortmarek/SwipeViewController#21]
I set three swipe buttons on my project. Since I don't need any navigation bar button item, do you know if there is any way to put the left swipe button close to the left side of the navigation view, and so does the right swipe button close to the right side of the navigation view ?

Thank you so much for the sharing!

**Comment by fortmarek** [comment]
I am sorry that I got to you so late. Anyway, it should be quite simple, just write this code in SwipeViewController subclass:
```swift
equalSpaces = false
setButtonsOffset(0, bottomOffset: 0)
```
