### ISSUE TITLE
How can I do without "didFinishLaunchingWithOptions"?

### ISSUE THREAD

**Issue by relaxsus** [fortmarek/SwipeViewController#26]
How can I do without "didFinishLaunchingWithOptions"? For example, how can I call my SwipeViewController in the viewDidAppear method? When the application starts, the first window I have authorization, and then I need to work with SwipeViewController.

**Comment by fortmarek** [comment]
You can init the SwipeViewController simply like this: 
```swift
let pageController = UIPageViewController(transitionStyle: .scroll, navigationOrientation: .horizontal, options: nil)
let navigationController = YourViewControllerName(rootViewController: pageController)
```
You can do this wherever you want, I guess I should make it more clear from the documentation.

**Comment by relaxsus** [comment]
`override func viewDidAppear(_ animated: Bool) {
        super .viewDidAppear(animated)
        
        let pageController = UIPageViewController(transitionStyle: .scroll, navigationOrientation: .horizontal, options: nil)
        let navigationController = ViewController(rootViewController: pageController)
        self.present(navigationController, animated:false, completion: nil)
        
    }`

this code does not work :( Please tell me what my mistake is, or how to write better :( I'm a beginner programmer, please forgive me :(

**Comment by fortmarek** [comment]
And what exactly does not work? I tried to present SwipeViewController in my code and it worked. Maybe there is something wrong in your ViewController regarding the setting of SwipeViewController.

**Comment by fortmarek** [comment]
But if you have authorization window, I think it would be better to first set AuthorizationViewController and then set it rootViewController to whatever your next viewcontroller is. Like this: 
```swift 
let window = UIApplication.shared.keyWindow
window?.rootViewController = YourViewController()
window?.makeKeyAndVisible()
```

**Comment by relaxsus** [comment]
Only the first screen is shown, but nothing is pressed. If you put 'animation = true', then an infinite number of times

**Comment by fortmarek** [comment]
...are you calling that in ViewController? Because then it would make sense (every time the view appears, it calls viewDidAppear again, etc., etc.)

**Comment by relaxsus** [comment]
Yes, you are right. How then to be? at what point it is better to call?

**Comment by fortmarek** [comment]
I do not really understand what you are trying to achieve. You said that you have an authorizationviewcontroller from which you want to present SwipeViewController, is that right?
Well, then in you AuthorizationViewController, for example when user taps loginButton, present SwipeViewController.

**Comment by relaxsus** [comment]
Oh my God, forgive me for taking your time, I,ve found a mistake after your last message. That was such a petty mistake .... You are a wonderful person and a programmer! Thank you very much! Everything is working!

**Comment by fortmarek** [comment]
Great! Glad to be of help, hit me up if you encounter any more problems 😉

**Comment by relaxsus** [comment]
![2017-12-18 18 13 55](https://user-images.githubusercontent.com/11596203/34113593-43997654-e421-11e7-960c-2649cf928e86.jpg)
Could you tell me pleeeease, how I can add the TabBarController to the hierarchy? I mean that the main Navigation is my TabBar with bottom switching. And after that is SwipeViewController.

**Comment by fortmarek** [comment]
I do not use storyboard and I have not tried that yet, you have to basically replicate this part:
```swift 
let pageController = UIPageViewController(transitionStyle: .scroll, navigationOrientation: .horizontal, options: nil)
let navigationController = YourViewControllerName(rootViewController: pageController)
```
My guess is that it would go something like this:
TabBarController -> SwipeViewController -> (rootViewController) UIPageViewController

**Comment by relaxsus** [comment]
Good afternoon. Could you tell me please, how is it possible to write the code? :( I wrote this code, but it does not work, because I do not know how to process tabBar = ( I excuse me for taking your time :( 
`override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if (segue.identifier == "show") {
            if let tabBarController = segue.destination as? UITabBarController {
                let pageController = UIPageViewController(transitionStyle: .scroll, navigationOrientation: .horizontal, options: nil)
                let navigationController = ViewController(rootViewController: pageController)
                self.present(navigationController, animated: true, completion: nil)
            }
        }
    }`

**Comment by fortmarek** [comment]
Umm, you do not have to present navigationController from your tabBarController, that is handled by UIKit itself. Just set tabBarController.viewCountrollers = Array<YourViewControllers> and then present that tabBarController.

**Comment by relaxsus** [comment]
Yes, I eventually read a lot of information, and did the same. Therefore, I deleted the question. You are a great person. I feel uncomfortable. Thank you very much.

**Comment by fortmarek** [comment]
I see, I answered right from the email, so I did not notice it had been already deleted. Anyway, starting programming is a difficult task, so do not feel bad for asking questions and no question is stupid. Keep learning ✌

**Comment by fortmarek** [comment]
I see, I answered right from the email, so I did not notice it had been already deleted. Anyway, starting programming is a difficult task, so do not feel bad for asking questions and no question is stupid. Keep learning ✌
