### ISSUE TITLE
NavigationBar bug ?!

### ISSUE THREAD

**Issue by relaxsus** [fortmarek/SwipeViewController#28]
Hello! I have a SwipeVC. It`s first window is MenuVC. 

SwipeVC navBar
<img width="323" alt="2018-02-27 17 10 19" src="https://user-images.githubusercontent.com/11596203/36733336-57f10250-1be1-11e8-9216-599a110c2854.png">

From it I go to VC1. 
```swift
self.performSegue(withIdentifier: "writeToDeveloperSegue", sender: self)
```
From VC1, I show the ImagePicker modal window.
```swift
present(imagePickerController, animated: true, completion: nil)
```
NavigationBar VC1
<img width="323" alt="2018-02-27 17 10 31" src="https://user-images.githubusercontent.com/11596203/36733360-67b67cf6-1be1-11e8-8478-2a2576f9fd70.png">

When I close modal within dismiss method of ImagePicker
```swift
imagePicker.dismiss(animated: true, completion: nil)
```
Navigation bar from SwipeVC  is displayed instead of VC1 navigation bar. 

NavigationBar VC1 after dismiss ImagePicker
<img width="322" alt="2018-02-27 17 10 44" src="https://user-images.githubusercontent.com/11596203/36733392-875ef52e-1be1-11e8-9cb4-4f99e73bb912.png">

Do you have any ideas how to deal with that or what am I doing wrong?

![giphy](https://user-images.githubusercontent.com/11596203/36781726-cfdec684-1c87-11e8-85c2-de1a14bc740b.gif)

**Comment by relaxsus** [comment]
Perhaps one of you will have a thought, in which direction to seek a solution to this problem, write please !?

**Comment by relaxsus** [comment]
[Decision](https://stackoverflow.com/questions/49110979/when-i-dismiss-the-modal-window-i-see-the-navigation-bar-of-the-previous-window#comment85229355_49111171)

**Comment by fortmarek** [comment]
Hello, sorry, I couldn't get to you earlier, but please note that as a maintainer I do this in my free time for free and I have been unfortunately quite busy lately. Anyway, thanks for using the project, I will try to deal with this in next release.
