### ISSUE TITLE
This was the error I got when I ran carthage update SwipeViewController  

### ISSUE THREAD

**Issue by vernonmatthew** [fortmarek/SwipeViewController#29]
Dependency "SwipeViewController" has no shared framework schemes

**Comment by vernonmatthew** [comment]
This was the error I got when I ran carthage update SwipeViewController

**Comment by fortmarek** [comment]
I'll look into it.

**Comment by fortmarek** [comment]
Could you try it now?

**Comment by vernonmatthew** [comment]
I'll go to

在 2018-03-14 18:51:39，"Marek Fořt" <notifications@github.com> 写道：


Could you try it now?

**Comment by vernonmatthew** [comment]
I'm sorry, but it's the same mistake.









在 2018-03-14 18:51:39，"Marek Fořt" <notifications@github.com> 写道：


Could you try it now?

**Comment by fortmarek** [comment]
Hmm, could you point to the latest commit? I have not made a new release.

**Comment by fortmarek** [comment]
It works for me, I'll push it as a new release and that should do it. Tell me if it works and I will close this issue.
