### ISSUE TITLE
Crash - CGColor not defined for the UIColor

### ISSUE THREAD

**Issue by gariera** [fortmarek/SwipeViewController#6]
Hi, could you see this crash pls? It occurs when it´s instantiated the SwipeViewController. Without adding any page or setting anything as the documentation explains. The only thing I do is inherit my VC from SwipeViewController

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -CGColor not defined for the UIColor <UIPlaceholderColor: 0x7912ebd0>; need to first convert colorspace.'

Thanks !!

**Comment by fortmarek** [comment]
Try using the setSelectionBar function where you would set the UIColor (it must be in viewDidLoad of your VC).

**Comment by gariera** [comment]
Thanks ! that fix the crash I mentioned. Anyway it has some other bugs (At least for me), I would suggest to make a revision of this pod. 

Many thanks for sharing it.

Best,

**Comment by fortmarek** [comment]
I'll keep improving it, I'm aware it's not perfect.
