### ISSUE TITLE
Crash when swipe

### ISSUE THREAD

**Issue by khuong291** [fortmarek/SwipeViewController#7]
![screen shot 2016-03-31 at 8 12 05 pm](https://cloud.githubusercontent.com/assets/11523438/14181613/d580ae08-f791-11e5-8402-3ccce6dfc8e5.png)
Sometime when I click these button in the navigation bar, it crashes

**Comment by fortmarek** [comment]
Which buttons? The top SwipeButtons?

**Comment by khuong291** [comment]
Please check my update

**Comment by fortmarek** [comment]
OK, this should not be such a difficult fix but I'm not at home right now. You can use it as you wish for now, I'll definitely publish new version on Saturday or Sunday (so don't worry about the error)

**Comment by khuong291** [comment]
Nice, I am using it, work find :). Keep your good work :+1:

**Comment by fortmarek** [comment]
Published new release, tell me if the fix works for you.
