### ISSUE TITLE
Crash when initial view controller should be the first view controller

### ISSUE THREAD

**Issue by HansZaa** [fortmarek/SwipeViewController#8]
Hi,

In your samples you use setFirstViewController(1) to make the SwipeViewController start on the second view controller.

If you change this to setFirstViewController(0) (or leave out that line, because 0 is the default value) the SwipeViewController starts without a view controller selected. As soon as you try to swipe, it crashes.

I have found the issue. Line 83 of SwipeViewController.swift reads
`guard currentPageIndex > 1 else {return}`
but it should be
`guard currentPageIndex >= 1 else {return}`

Kind regards,
Hans

**Comment by fortmarek** [comment]
Thank you very much, really appreciated, it's fixed now.
